'use strict';
/**
 * tests/agents-compile-claude-target-byte-match.test.cjs — Phase 52 SC1 LOCK
 *
 * BACKWARD-COMPATIBILITY LOCK TEST.
 *
 * For every gsd-*.md agent committed at HEAD (dynamically enumerated via
 * fs.readdirSync of agents/ — see TK-1705; previously a hardcoded 22-name
 * list that went stale the moment the 3 Phase-61 persona agents landed,
 * gsd-persona-senior-backend, gsd-persona-frontend-specialist,
 * gsd-persona-systems-architect):
 *   1. Read the current bytes from agents/<name>.md (utf-8)
 *   2. Run compile('claude-code', { source: 'get-shit-done/agents', outDir: <tmp> })
 *   3. Read the regenerated bytes from <tmp>/<name>.md
 *   4. Assert byte-for-byte equality
 *
 * HALT-AND-DIVERGE policy: if even ONE byte differs, this test fails.
 * The agents/*.md file is the canonical source of truth. DO NOT fix the diff
 * by editing agents/<name>.md or get-shit-done/agents/<name>/AGENT.yaml directly.
 * Instead, route back to:
 *   - scripts/agent-compiler.cjs (fix the compiler emitter)
 *   - scripts/agent-md-to-yaml.cjs (fix the converter if the YAML lost data)
 *
 * Run: node --test tests/agents-compile-claude-target-byte-match.test.cjs
 *
 * Budget: under 5 seconds total for all agents.
 * No network, no PG, no subprocess — pure in-process compile.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const ROOT = path.resolve(__dirname, '..');
const AGENTS_DIR = path.join(ROOT, 'agents');
const COMPILER = path.join(ROOT, 'scripts', 'agent-compiler.cjs');
const { compile } = require(COMPILER);

// Dynamically enumerate all gsd-*.md agent files in agents/ (alphabetical),
// rather than hardcoding a fixed list that goes stale on every roster change.
function listAgentNames() {
  return fs.readdirSync(AGENTS_DIR)
    .filter((f) => /^gsd-.*\.md$/.test(f))
    .map((f) => f.replace(/\.md$/, ''))
    .sort();
}

const AGENT_NAMES = listAgentNames();

// ─── SC1 BYTE-MATCH LOCK ──────────────────────────────────────────────────────

test(`SC1 byte-match: compile(claude-code) is byte-for-byte identical to agents/*.md for all ${AGENT_NAMES.length} agents`, (t) => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-byte-match-'));

  t.after(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (_) {}
  });

  // Compile all agents to temp dir
  const result = compile('claude-code', {
    source: path.join(ROOT, 'get-shit-done/agents'),
    outDir: tmpDir,
  });

  assert.equal(
    result.errors.length, 0,
    `compile() must produce 0 errors. Got: ${JSON.stringify(result.errors)}`
  );
  assert.equal(
    result.compiled.length, AGENT_NAMES.length,
    `compile() must produce exactly ${AGENT_NAMES.length} outputs. Got: ${result.compiled.length}`
  );
  assert.equal(
    result.skipped.length, 0,
    `compile() must skip 0 agents. Got skipped: ${result.skipped.map(s => s.name).join(', ')}`
  );

  // byte-for-byte comparison for each agent
  const diffs = [];

  for (const agentName of AGENT_NAMES) {
    const canonicalPath = path.join(ROOT, 'agents', `${agentName}.md`);
    const generatedPath = path.join(tmpDir, `${agentName}.md`);

    // Read canonical bytes (committed agents/*.md)
    let canonical;
    try {
      canonical = fs.readFileSync(canonicalPath, 'utf8');
    } catch (e) {
      diffs.push(`${agentName}: MISSING canonical file at ${canonicalPath}`);
      continue;
    }

    // Read generated bytes from compiler output
    let generated;
    try {
      generated = fs.readFileSync(generatedPath, 'utf8');
    } catch (e) {
      diffs.push(`${agentName}: MISSING generated file at ${generatedPath}`);
      continue;
    }

    if (canonical !== generated) {
      // Locate first byte difference for diagnostic message
      let firstDiffByte = -1;
      for (let i = 0; i < Math.min(canonical.length, generated.length); i++) {
        if (canonical[i] !== generated[i]) {
          firstDiffByte = i;
          break;
        }
      }

      const lenMsg = canonical.length !== generated.length
        ? ` (length: canonical=${canonical.length} generated=${generated.length})`
        : '';

      let ctxMsg = '';
      if (firstDiffByte >= 0) {
        const ctxStart = Math.max(0, firstDiffByte - 20);
        const ctxEnd = Math.min(canonical.length, firstDiffByte + 40);
        ctxMsg = ` | byte ${firstDiffByte}${lenMsg}`
          + ` | canonical[${ctxStart}:${ctxEnd}]=${JSON.stringify(canonical.slice(ctxStart, ctxEnd))}`
          + ` | generated[${ctxStart}:${Math.min(generated.length, ctxEnd)}]=${JSON.stringify(generated.slice(ctxStart, Math.min(generated.length, ctxEnd)))}`;
      } else if (canonical.length !== generated.length) {
        ctxMsg = lenMsg;
      }

      diffs.push(`${agentName}: byte mismatch${ctxMsg}`);
    }
  }

  // Strict equality: ALL 22 agents must byte-match
  assert.strictEqual(
    diffs.length, 0,
    `SC1 byte-match FAILED for ${diffs.length} agent(s):\n${diffs.join('\n')}\n\n` +
    `HALT-AND-DIVERGE: do NOT edit agents/*.md or AGENT.yaml to fix this.\n` +
    `Route to: scripts/agent-compiler.cjs (fix emitter) OR scripts/agent-md-to-yaml.cjs (fix converter).`
  );
});
