'use strict';
/**
 * tests/agents-compile-claude-target-byte-match.test.cjs — Phase 52 SC1 LOCK
 *
 * BACKWARD-COMPATIBILITY LOCK TEST.
 *
 * For each of the 22 agents committed at HEAD (17 locked at HEAD 21438ae +
 * 5 new agents added by the 2026-07-02/03 roster expansion: gsd-executor-ai,
 * gsd-executor-mobile-android, gsd-executor-mobile-cross,
 * gsd-executor-mobile-ios, gsd-executor-wearables):
 *   1. Read the current bytes from agents/<name>.md (utf-8)
 *   2. Run compile('claude-code', { source: 'get-shit-done/agents', outDir: <tmp> })
 *   3. Read the regenerated bytes from <tmp>/<name>.md
 *   4. Assert byte-for-byte equality
 *
 * HALT-AND-DIVERGE policy: if even ONE byte differs, this test fails.
 * The agents/*.md file is the canonical source of truth. DO NOT fix the diff
 * by editing agents/<name>.md or get-shit-done/agents/<name>/AGENT.yaml directly.
 * Instead, route back to:
 *   - scripts/agent-compiler.cjs (fix the compiler emitter)
 *   - scripts/agent-md-to-yaml.cjs (fix the converter if the YAML lost data)
 *
 * Run: node --test tests/agents-compile-claude-target-byte-match.test.cjs
 *
 * Budget: under 5 seconds total for all 22 agents.
 * No network, no PG, no subprocess — pure in-process compile.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const ROOT = path.resolve(__dirname, '..');
const COMPILER = path.join(ROOT, 'scripts', 'agent-compiler.cjs');
const { compile } = require(COMPILER);

// The 22 agent names committed at HEAD (17 locked per HEAD 21438ae + 5 added
// by the 2026-07-02/03 roster expansion), alphabetical order.
const AGENT_NAMES = [
  'gsd-architect',
  'gsd-checker',
  'gsd-debugger',
  'gsd-executor-ai',
  'gsd-executor-backend',
  'gsd-executor-data',
  'gsd-executor-frontend',
  'gsd-executor-general',
  'gsd-executor-infra',
  'gsd-executor-mobile-android',
  'gsd-executor-mobile-cross',
  'gsd-executor-mobile-ios',
  'gsd-executor-wearables',
  'gsd-operator',
  'gsd-planner',
  'gsd-qa',
  'gsd-researcher',
  'gsd-reviewer',
  'gsd-roadmapper',
  'gsd-security',
  'gsd-tester',
  'gsd-validator',
];

// ─── SC1 BYTE-MATCH LOCK ──────────────────────────────────────────────────────

test('SC1 byte-match: compile(claude-code) is byte-for-byte identical to agents/*.md for all 22 agents', (t) => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-byte-match-'));

  t.after(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (_) {}
  });

  // Compile all 22 agents to temp dir
  const result = compile('claude-code', {
    source: path.join(ROOT, 'get-shit-done/agents'),
    outDir: tmpDir,
  });

  assert.equal(
    result.errors.length, 0,
    `compile() must produce 0 errors. Got: ${JSON.stringify(result.errors)}`
  );
  assert.equal(
    result.compiled.length, 22,
    `compile() must produce exactly 22 outputs. Got: ${result.compiled.length}`
  );
  assert.equal(
    result.skipped.length, 0,
    `compile() must skip 0 agents. Got skipped: ${result.skipped.map(s => s.name).join(', ')}`
  );

  // byte-for-byte comparison for each agent
  const diffs = [];

  for (const agentName of AGENT_NAMES) {
    const canonicalPath = path.join(ROOT, 'agents', `${agentName}.md`);
    const generatedPath = path.join(tmpDir, `${agentName}.md`);

    // Read canonical bytes (committed agents/*.md)
    let canonical;
    try {
      canonical = fs.readFileSync(canonicalPath, 'utf8');
    } catch (e) {
      diffs.push(`${agentName}: MISSING canonical file at ${canonicalPath}`);
      continue;
    }

    // Read generated bytes from compiler output
    let generated;
    try {
      generated = fs.readFileSync(generatedPath, 'utf8');
    } catch (e) {
      diffs.push(`${agentName}: MISSING generated file at ${generatedPath}`);
      continue;
    }

    if (canonical !== generated) {
      // Locate first byte difference for diagnostic message
      let firstDiffByte = -1;
      for (let i = 0; i < Math.min(canonical.length, generated.length); i++) {
        if (canonical[i] !== generated[i]) {
          firstDiffByte = i;
          break;
        }
      }

      const lenMsg = canonical.length !== generated.length
        ? ` (length: canonical=${canonical.length} generated=${generated.length})`
        : '';

      let ctxMsg = '';
      if (firstDiffByte >= 0) {
        const ctxStart = Math.max(0, firstDiffByte - 20);
        const ctxEnd = Math.min(canonical.length, firstDiffByte + 40);
        ctxMsg = ` | byte ${firstDiffByte}${lenMsg}`
          + ` | canonical[${ctxStart}:${ctxEnd}]=${JSON.stringify(canonical.slice(ctxStart, ctxEnd))}`
          + ` | generated[${ctxStart}:${Math.min(generated.length, ctxEnd)}]=${JSON.stringify(generated.slice(ctxStart, Math.min(generated.length, ctxEnd)))}`;
      } else if (canonical.length !== generated.length) {
        ctxMsg = lenMsg;
      }

      diffs.push(`${agentName}: byte mismatch${ctxMsg}`);
    }
  }

  // Strict equality: ALL 22 agents must byte-match
  assert.strictEqual(
    diffs.length, 0,
    `SC1 byte-match FAILED for ${diffs.length} agent(s):\n${diffs.join('\n')}\n\n` +
    `HALT-AND-DIVERGE: do NOT edit agents/*.md or AGENT.yaml to fix this.\n` +
    `Route to: scripts/agent-compiler.cjs (fix emitter) OR scripts/agent-md-to-yaml.cjs (fix converter).`
  );
});
